import './globals.css';
import { Open_Sans } from 'next/font/google';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import PocketBase from 'pocketbase';

const openSans = Open_Sans({ weight: '300' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function getData() {
  const pb = new PocketBase('http://127.0.0.1:8090');
  const records = await pb.collection('navigation').getOne('00navigation-de');
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.

  console.log(records.value);

  return records;
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const data = await getData();

  return (
    <html lang="en">
      <body>
        <div className="flex flex-col items-center justify-between px-24 min-h-screen">
          {/* @ts-ignore */}
          <Header items={data.value} />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
